# Generated by Django 5.2 on 2025-08-29 13:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Padron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=12)),
                ('sexo', models.CharField(max_length=1)),
                ('ayn', models.CharField(blank=True, max_length=255, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=255, null=True)),
                ('subcomando', models.IntegerField(blank=True, null=True)),
                ('seccion', models.IntegerField(blank=True, null=True)),
                ('circuito', models.CharField(blank=True, max_length=10, null=True)),
                ('mesa', models.IntegerField(db_index=True)),
                ('orden', models.CharField(db_index=True, max_length=3)),
                ('id_escuela', models.IntegerField(blank=True, null=True)),
                ('escuela', models.CharField(blank=True, max_length=255, null=True)),
                ('domicilio_escuela', models.CharField(blank=True, max_length=255, null=True)),
                ('voto', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'padron',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VotoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa', models.IntegerField()),
                ('orden', models.CharField(max_length=3)),
                ('dni', models.CharField(max_length=12)),
                ('accion', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'voto_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IntegrationOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('voto_registrado', 'voto_registrado')], max_length=64)),
                ('payload', models.JSONField()),
                ('estado', models.CharField(choices=[('pending', 'pending'), ('sent', 'sent'), ('error', 'error')], default='pending', max_length=16)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'integrations_outbox',
                'indexes': [models.Index(fields=['estado'], name='integration_estado_8169fc_idx')],
            },
        ),
    ]
