# Generated by Django 5.2 on 2025-09-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adherente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'No binario')], max_length=1)),
                ('apellido', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('domicilio', models.CharField(max_length=255)),
                ('circuito', models.CharField(max_length=100)),
                ('cod_localidad', models.CharField(blank=True, max_length=20, null=True)),
                ('apellido_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('voto', models.BooleanField(default=False)),
                ('creado_por', models.IntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('referente', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('localidad_donde_reside', models.CharField(blank=True, max_length=100, null=True)),
                ('localidad_donde_vota', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'adherentes',
                'managed': False,
            },
        ),
    ]
