# Generated by Django 5.2 on 2025-09-12 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_updated_at'),
    ]

    operations = [
    ]
