# Generated by Django 5.1.7 on 2025-05-05 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electores_votaron', models.PositiveIntegerField()),
                ('sobres_encontrados', models.PositiveIntegerField()),
                ('diferencia', models.IntegerField()),
                ('escrutada', models.BooleanField(default=False)),
                ('mesa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resumen', to='elecciones.mesa')),
            ],
        ),
        migrations.CreateModel(
            name='VotoMesaCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votos', models.PositiveIntegerField()),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_cargo', to='elecciones.mesa')),
                ('partido_postulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='elecciones.partidopostulacion')),
            ],
            options={
                'unique_together': {('mesa', 'partido_postulacion')},
            },
        ),
        migrations.CreateModel(
            name='VotoMesaEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('blanco', 'En blanco'), ('nulo', 'Nulo'), ('recurrido', 'Recurrido'), ('impugnado', 'Impugnado'), ('comando', 'Comando')], max_length=20)),
                ('votos', models.PositiveIntegerField()),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_especiales', to='elecciones.cargopostulacion')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_especiales', to='elecciones.mesa')),
            ],
            options={
                'unique_together': {('mesa', 'cargo', 'tipo')},
            },
        ),
    ]
