# Generated by Django 5.1.7 on 2025-05-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0002_resumenmesa_votomesacargo_votomesaespecial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='escrutada',
            field=models.BooleanField(default=False),
        ),
    ]
