# Generated by Django 5.1.7 on 2025-05-05 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0003_mesa_escrutada'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='votomesaespecial',
            unique_together={('mesa', 'tipo')},
        ),
        migrations.RemoveField(
            model_name='votomesaespecial',
            name='cargo',
        ),
    ]
