# Generated by Django 5.2 on 2025-08-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0004_alter_votomesaespecial_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escuela',
            name='numero_escuela',
        ),
        migrations.AlterField(
            model_name='circuito',
            name='numero_circuito',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
