# Generated by Django 5.2 on 2025-08-20 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0005_remove_escuela_numero_escuela_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcomando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_subcomando', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Subcomando',
                'verbose_name_plural': 'Subcomandos',
            },
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='circuito',
        ),
        migrations.RemoveField(
            model_name='escuela',
            name='circuito',
        ),
        migrations.AlterModelOptions(
            name='escuela',
            options={'verbose_name': 'Escuela', 'verbose_name_plural': 'Escuelas'},
        ),
        migrations.AlterModelOptions(
            name='mesa',
            options={'verbose_name': 'Mesa', 'verbose_name_plural': 'Mesas'},
        ),
        migrations.AlterModelOptions(
            name='partido',
            options={'ordering': ['orden', 'numero_lista']},
        ),
        migrations.AlterUniqueTogether(
            name='votomesaespecial',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='partido',
            name='orden',
            field=models.IntegerField(blank=True, db_column='orden', db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='escuela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='elecciones.escuela'),
        ),
        migrations.AddField(
            model_name='votomesaespecial',
            name='cargo_postulacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votos_especiales', to='elecciones.cargopostulacion'),
        ),
        migrations.AlterField(
            model_name='votomesaespecial',
            name='tipo',
            field=models.CharField(choices=[('blanco', 'En blanco'), ('impugnado', 'Impugnado')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='votomesaespecial',
            unique_together={('mesa', 'cargo_postulacion', 'tipo')},
        ),
        migrations.AddField(
            model_name='escuela',
            name='subcomando',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escuelas', to='elecciones.subcomando'),
        ),
        migrations.DeleteModel(
            name='Circuito',
        ),
    ]
