# Generated by Django 5.2 on 2025-08-20 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0006_subcomando_remove_mesa_circuito_and_more'),
    ]

    operations = [
    ]
