# Generated by Django 5.2 on 2025-08-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0007_add_orden_to_partido'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='numero_mesa',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='partidopostulacion',
            index=models.Index(fields=['cargo_postulacion', 'partido'], name='elecciones__cargo_p_cf0039_idx'),
        ),
        migrations.AddIndex(
            model_name='votomesacargo',
            index=models.Index(fields=['partido_postulacion'], name='elecciones__partido_9f63ee_idx'),
        ),
        migrations.AddIndex(
            model_name='votomesacargo',
            index=models.Index(fields=['mesa'], name='elecciones__mesa_id_9497f5_idx'),
        ),
        migrations.AddIndex(
            model_name='votomesaespecial',
            index=models.Index(fields=['cargo_postulacion'], name='elecciones__cargo_p_87807c_idx'),
        ),
        migrations.AddIndex(
            model_name='votomesaespecial',
            index=models.Index(fields=['mesa'], name='elecciones__mesa_id_a75106_idx'),
        ),
    ]
