# Generated by Django 5.2 on 2025-08-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0008_user_last_seen_alter_mesa_numero_mesa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='celular',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
