# Generated by Django 5.2 on 2025-08-29 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0009_user_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('operador', 'Operador'), ('panelista', 'Panelista'), ('admin', 'Administrador'), ('marcador', 'Marcador')], default='operador', max_length=20),
        ),
        migrations.CreateModel(
            name='Marcador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcadores', to='elecciones.mesa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas_habilitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marcador',
                'verbose_name_plural': 'Marcadores',
                'indexes': [models.Index(fields=['user', 'mesa'], name='elecciones__user_id_be5521_idx')],
                'unique_together': {('user', 'mesa')},
            },
        ),
    ]
