# Generated by Django 5.2 on 2025-08-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0010_alter_user_role_marcador'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='marcador',
            name='elecciones__user_id_be5521_idx',
        ),
        migrations.AlterUniqueTogether(
            name='marcador',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='marcador',
            constraint=models.UniqueConstraint(fields=('user', 'mesa'), name='uniq_user_mesa'),
        ),
        migrations.AddConstraint(
            model_name='marcador',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('user',), name='uniq_user_activo'),
        ),
    ]
