# Generated by Django 5.2 on 2025-08-30 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0011_remove_marcador_elecciones__user_id_be5521_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcacionTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.CharField(max_length=3)),
                ('dni', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcaciones_temp', to='elecciones.mesa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcaciones_temp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
