# Generated by Django 5.2 on 2025-08-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0012_marcaciontemp'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='marcaciontemp',
            constraint=models.UniqueConstraint(fields=('user', 'mesa', 'orden'), name='uniq_marcacion_temp'),
        ),
    ]
