# Generated by Django 5.2 on 2025-09-05 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0014_circuito_seccion_escuela_circuito_circuito_seccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subcomando',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='elecciones.subcomando'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('operador', 'Operador'), ('panelista', 'Panelista'), ('admin', 'Administrador'), ('marcador', 'Marcador'), ('subcomando', 'Responsable de Subcomando')], default='operador', max_length=20),
        ),
    ]
