# Generated by Django 5.2 on 2025-09-05 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0015_user_subcomando_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('operador', 'Operador'), ('panelista', 'Panelista'), ('admin', 'Administrador'), ('marcador', 'Marcador'), ('subcomando', 'Responsable de Subcomando'), ('computos', 'Cómputos')], default='operador', max_length=20),
        ),
    ]
