# Generated by Django 5.2 on 2025-10-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0016_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votomesaespecial',
            name='tipo',
            field=models.CharField(choices=[('blanco', 'En blanco'), ('impugnado', 'Impugnado'), ('nulo', 'Nulo'), ('recurrido', 'Recurrido'), ('identidad_impugnada', 'Identidad Impugnada')], max_length=25),
        ),
    ]
